/**
 * CTFL Mock Exam backend — Google Apps Script Web App.
 *
 * Deploy: script.google.com > New project > paste this file > Deploy > New deployment >
 * type "Web app" > Execute as "Me" > Who has access "Anyone" > Deploy > copy the /exec URL
 * into CTFL_Mock_Exam.html's APPS_SCRIPT_URL constant.
 *
 * Fill in SHEET_ID below with the target spreadsheet's ID (the long string in its URL).
 * Sheet tabs "CTFL_Registrations" and "CTFL_Results" are created automatically on first use.
 */

// Defaults to the same spreadsheet already used by the Assessment/Consult forms
// (adds new tabs, doesn't touch the existing "Result"/"Consult" tabs). Change this
// if you'd rather keep exam data in its own separate spreadsheet.
const SHEET_ID = '1_2w2iLlNv_Mv6cP2eMfUzO6OBpKFJheSiNHkO0enj_8';
const REGISTRATIONS_TAB = 'CTFL_Registrations';
const RESULTS_TAB = 'CTFL_Results';
const PASS_PERCENTAGE = 65;

// Team-only preview gate — must match GATE_PASSWORD in CTFL_Mock_Exam.html.
// Remove this check (and the matching client-side gate) once the page is public.
const GATE_PASSWORD = 'Jakarta2026';

// Admin panel password — separate audience from GATE_PASSWORD above (site admin,
// not exam-taker). Must match ADMIN_PASSWORD in Admin.html. Checked here too so
// admin actions are protected even if someone bypasses the client-side check.
const ADMIN_PASSWORD = 'Topan804';

const ARTICLES_TAB = 'NgobrolQA_Articles';
const ARTICLE_COLUMNS = ['article_id', 'slug', 'title', 'body_html', 'status', 'created_at', 'updated_at'];
const ARTICLE_IMAGES_FOLDER_NAME = 'NgobrolQA Article Images';

// Generated by scripts/export_for_ngobrolqa.py from data/questions.csv — paste the contents
// of answer-key.gs.txt here (replacing the placeholder below) whenever questions.csv changes.
const ANSWER_KEY = {"A-1": {"correct": "c", "points": 1}, "A-2": {"correct": "a", "points": 1}, "A-3": {"correct": "a", "points": 1}, "A-4": {"correct": "b", "points": 1}, "A-5": {"correct": "b", "points": 1}, "A-6": {"correct": "a,e", "points": 1}, "A-7": {"correct": "b", "points": 1}, "A-8": {"correct": "d", "points": 1}, "A-9": {"correct": "d", "points": 1}, "A-10": {"correct": "c", "points": 1}, "A-11": {"correct": "d", "points": 1}, "A-12": {"correct": "c", "points": 1}, "A-13": {"correct": "a", "points": 1}, "A-14": {"correct": "b", "points": 1}, "A-15": {"correct": "a", "points": 1}, "A-16": {"correct": "d", "points": 1}, "A-17": {"correct": "b", "points": 1}, "A-18": {"correct": "d", "points": 1}, "A-19": {"correct": "c", "points": 1}, "A-20": {"correct": "b", "points": 1}, "A-21": {"correct": "a", "points": 1}, "A-22": {"correct": "d", "points": 1}, "A-23": {"correct": "d", "points": 1}, "A-24": {"correct": "a", "points": 1}, "A-25": {"correct": "d", "points": 1}, "A-26": {"correct": "a", "points": 1}, "A-27": {"correct": "c", "points": 1}, "A-28": {"correct": "b", "points": 1}, "A-29": {"correct": "a", "points": 1}, "A-30": {"correct": "c", "points": 1}, "A-31": {"correct": "c,e", "points": 1}, "A-32": {"correct": "d", "points": 1}, "A-33": {"correct": "a", "points": 1}, "A-34": {"correct": "a", "points": 1}, "A-35": {"correct": "c", "points": 1}, "A-36": {"correct": "d", "points": 1}, "A-37": {"correct": "c", "points": 1}, "A-38": {"correct": "c", "points": 1}, "A-39": {"correct": "c", "points": 1}, "A-40": {"correct": "b", "points": 1}, "B-1": {"correct": "d", "points": 1}, "B-2": {"correct": "b", "points": 1}, "B-3": {"correct": "d", "points": 1}, "B-4": {"correct": "a", "points": 1}, "B-5": {"correct": "c", "points": 1}, "B-6": {"correct": "b", "points": 1}, "B-7": {"correct": "b", "points": 1}, "B-8": {"correct": "d", "points": 1}, "B-9": {"correct": "b", "points": 1}, "B-10": {"correct": "b", "points": 1}, "B-11": {"correct": "a", "points": 1}, "B-12": {"correct": "b", "points": 1}, "B-13": {"correct": "a", "points": 1}, "B-14": {"correct": "d", "points": 1}, "B-15": {"correct": "b", "points": 1}, "B-16": {"correct": "c", "points": 1}, "B-17": {"correct": "d", "points": 1}, "B-18": {"correct": "c", "points": 1}, "B-19": {"correct": "d", "points": 1}, "B-20": {"correct": "a", "points": 1}, "B-21": {"correct": "d", "points": 1}, "B-22": {"correct": "b", "points": 1}, "B-23": {"correct": "c", "points": 1}, "B-24": {"correct": "b", "points": 1}, "B-25": {"correct": "c", "points": 1}, "B-26": {"correct": "a,e", "points": 1}, "B-27": {"correct": "d", "points": 1}, "B-28": {"correct": "b", "points": 1}, "B-29": {"correct": "d", "points": 1}, "B-30": {"correct": "a", "points": 1}, "B-31": {"correct": "b", "points": 1}, "B-32": {"correct": "b", "points": 1}, "B-33": {"correct": "d", "points": 1}, "B-34": {"correct": "c", "points": 1}, "B-35": {"correct": "a", "points": 1}, "B-36": {"correct": "a", "points": 1}, "B-37": {"correct": "a", "points": 1}, "B-38": {"correct": "b", "points": 1}, "B-39": {"correct": "c", "points": 1}, "B-40": {"correct": "a", "points": 1}, "C-1": {"correct": "b", "points": 1}, "C-2": {"correct": "c", "points": 1}, "C-3": {"correct": "b", "points": 1}, "C-4": {"correct": "b,e", "points": 1}, "C-5": {"correct": "a", "points": 1}, "C-6": {"correct": "c", "points": 1}, "C-7": {"correct": "b", "points": 1}, "C-8": {"correct": "a", "points": 1}, "C-9": {"correct": "d", "points": 1}, "C-10": {"correct": "d", "points": 1}, "C-11": {"correct": "b", "points": 1}, "C-12": {"correct": "c", "points": 1}, "C-13": {"correct": "d", "points": 1}, "C-14": {"correct": "b", "points": 1}, "C-15": {"correct": "d", "points": 1}, "C-16": {"correct": "a", "points": 1}, "C-17": {"correct": "b", "points": 1}, "C-18": {"correct": "b", "points": 1}, "C-19": {"correct": "c", "points": 1}, "C-20": {"correct": "a", "points": 1}, "C-21": {"correct": "d", "points": 1}, "C-22": {"correct": "d", "points": 1}, "C-23": {"correct": "a", "points": 1}, "C-24": {"correct": "c", "points": 1}, "C-25": {"correct": "a", "points": 1}, "C-26": {"correct": "b", "points": 1}, "C-27": {"correct": "d", "points": 1}, "C-28": {"correct": "b", "points": 1}, "C-29": {"correct": "d", "points": 1}, "C-30": {"correct": "a", "points": 1}, "C-31": {"correct": "c", "points": 1}, "C-32": {"correct": "a", "points": 1}, "C-33": {"correct": "b", "points": 1}, "C-34": {"correct": "d", "points": 1}, "C-35": {"correct": "c", "points": 1}, "C-36": {"correct": "b", "points": 1}, "C-37": {"correct": "d", "points": 1}, "C-38": {"correct": "b", "points": 1}, "C-39": {"correct": "d", "points": 1}, "C-40": {"correct": "d", "points": 1}, "D-1": {"correct": "d", "points": 1}, "D-2": {"correct": "c", "points": 1}, "D-3": {"correct": "a", "points": 1}, "D-4": {"correct": "b", "points": 1}, "D-5": {"correct": "a", "points": 1}, "D-6": {"correct": "d", "points": 1}, "D-7": {"correct": "a", "points": 1}, "D-8": {"correct": "b", "points": 1}, "D-9": {"correct": "a", "points": 1}, "D-10": {"correct": "a", "points": 1}, "D-11": {"correct": "d", "points": 1}, "D-12": {"correct": "b", "points": 1}, "D-13": {"correct": "a", "points": 1}, "D-14": {"correct": "b", "points": 1}, "D-15": {"correct": "c", "points": 1}, "D-16": {"correct": "c", "points": 1}, "D-17": {"correct": "b", "points": 1}, "D-18": {"correct": "b", "points": 1}, "D-19": {"correct": "b", "points": 1}, "D-20": {"correct": "b,e", "points": 1}, "D-21": {"correct": "c", "points": 1}, "D-22": {"correct": "a", "points": 1}, "D-23": {"correct": "b", "points": 1}, "D-24": {"correct": "c", "points": 1}, "D-25": {"correct": "a", "points": 1}, "D-26": {"correct": "c", "points": 1}, "D-27": {"correct": "d", "points": 1}, "D-28": {"correct": "d", "points": 1}, "D-29": {"correct": "a", "points": 1}, "D-30": {"correct": "b,d", "points": 1}, "D-31": {"correct": "a", "points": 1}, "D-32": {"correct": "b", "points": 1}, "D-33": {"correct": "c", "points": 1}, "D-34": {"correct": "b", "points": 1}, "D-35": {"correct": "b,e", "points": 1}, "D-36": {"correct": "c", "points": 1}, "D-37": {"correct": "d", "points": 1}, "D-38": {"correct": "a", "points": 1}, "D-39": {"correct": "b", "points": 1}, "D-40": {"correct": "c", "points": 1}};

function getSheet_(tabName, headers) {
  const ss = SpreadsheetApp.openById(SHEET_ID);
  let sheet = ss.getSheetByName(tabName);
  if (!sheet) {
    sheet = ss.insertSheet(tabName);
    sheet.appendRow(headers);
  }
  return sheet;
}

function normalizeAnswer_(answer) {
  if (!answer) return '';
  return answer
    .split(',')
    .map(function (s) { return s.trim().toLowerCase(); })
    .filter(Boolean)
    .sort()
    .join(',');
}

function jsonResponse_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

function handleRegister_(data) {
  const name = (data.name || '').trim();
  const email = (data.email || '').trim();
  const phone = (data.phone || '').trim();
  if (!name || !email) {
    return { error: 'name and email are required' };
  }
  const userId = Utilities.getUuid();
  const sheet = getSheet_(REGISTRATIONS_TAB, ['user_id', 'name', 'email', 'phone', 'registered_at']);
  sheet.appendRow([userId, name, email, phone, new Date().toISOString()]);
  return { userId: userId, name: name, email: email };
}

function handleSubmit_(data) {
  const userId = data.userId;
  const name = data.name;
  const email = data.email;
  const examSet = (data.examSet || '').toUpperCase();
  const questionIds = data.questionIds || [];
  const answers = data.answers || {};
  const startedAt = data.startedAt || '';
  const finishedAt = data.finishedAt || new Date().toISOString();

  if (!userId || !name || !email || questionIds.length === 0) {
    return { error: 'userId, name, email, and questionIds are required' };
  }

  let score = 0;
  let totalPoints = 0;
  const review = [];

  for (let i = 0; i < questionIds.length; i++) {
    const qid = questionIds[i];
    const key = ANSWER_KEY[qid];
    if (!key) continue;
    totalPoints += key.points;
    const yourAnswer = normalizeAnswer_(answers[qid] || '');
    const correctAnswer = normalizeAnswer_(key.correct);
    const isCorrect = yourAnswer !== '' && yourAnswer === correctAnswer;
    if (isCorrect) score += key.points;
    review.push({ questionId: qid, yourAnswer: yourAnswer, correctAnswer: correctAnswer, isCorrect: isCorrect });
  }

  const percentage = totalPoints > 0 ? Math.round((score / totalPoints) * 10000) / 100 : 0;
  const passed = percentage >= PASS_PERCENTAGE;
  const durationSeconds = startedAt ? Math.round((new Date(finishedAt) - new Date(startedAt)) / 1000) : '';
  const resultId = Utilities.getUuid();

  const sheet = getSheet_(RESULTS_TAB, [
    'result_id', 'user_id', 'name', 'email', 'exam_set',
    'score', 'total_points', 'percentage', 'passed',
    'started_at', 'finished_at', 'duration_seconds', 'answers_json',
  ]);
  sheet.appendRow([
    resultId, userId, name, email, examSet,
    score, totalPoints, percentage, passed ? 'yes' : 'no',
    startedAt, finishedAt, durationSeconds, JSON.stringify(answers),
  ]);

  return {
    resultId: resultId,
    score: score,
    totalPoints: totalPoints,
    percentage: percentage,
    passed: passed,
    passPercentage: PASS_PERCENTAGE,
    review: review,
  };
}

function handleLeaderboard_() {
  const sheet = getSheet_(RESULTS_TAB, [
    'result_id', 'user_id', 'name', 'email', 'exam_set',
    'score', 'total_points', 'percentage', 'passed',
    'started_at', 'finished_at', 'duration_seconds', 'answers_json',
  ]);
  const rows = sheet.getDataRange().getValues();
  const headers = rows.shift();
  const idx = {};
  headers.forEach(function (h, i) { idx[h] = i; });

  const bestByEmail = {};
  rows.forEach(function (row) {
    const email = row[idx.email];
    if (!email) return;
    const pct = Number(row[idx.percentage]);
    const existing = bestByEmail[email];
    if (!existing || pct > existing.percentage) {
      bestByEmail[email] = {
        name: row[idx.name],
        email: email,
        examSet: row[idx.exam_set],
        score: Number(row[idx.score]),
        totalPoints: Number(row[idx.total_points]),
        percentage: pct,
        passed: row[idx.passed] === 'yes',
        finishedAt: row[idx.finished_at],
        durationSeconds: Number(row[idx.duration_seconds]) || Infinity,
      };
    }
  });

  const leaderboard = Object.keys(bestByEmail).map(function (email) { return bestByEmail[email]; });
  leaderboard.sort(function (a, b) {
    if (b.percentage !== a.percentage) return b.percentage - a.percentage;
    return a.durationSeconds - b.durationSeconds;
  });

  return { leaderboard: leaderboard };
}

function slugify_(text) {
  return String(text || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function articleRowsIndexed_() {
  const sheet = getSheet_(ARTICLES_TAB, ARTICLE_COLUMNS);
  const values = sheet.getDataRange().getValues();
  const headers = values.shift();
  const idx = {};
  headers.forEach(function (h, i) { idx[h] = i; });
  return { sheet: sheet, rows: values, idx: idx };
}

function handleListArticles_() {
  const data = articleRowsIndexed_();
  const articles = data.rows.map(function (row) {
    return {
      articleId: row[data.idx.article_id],
      slug: row[data.idx.slug],
      title: row[data.idx.title],
      status: row[data.idx.status],
      createdAt: row[data.idx.created_at],
      updatedAt: row[data.idx.updated_at],
    };
  });
  articles.sort(function (a, b) { return new Date(b.updatedAt) - new Date(a.updatedAt); });
  return { articles: articles };
}

// Public — no admin password required. Only ever returns a published article;
// drafts stay invisible to readers even if they guess/know the slug.
function handleGetArticle_(data) {
  const rowsData = articleRowsIndexed_();
  const idx = rowsData.idx;
  const match = rowsData.rows.find(function (row) {
    return row[idx.slug] === data.slug && row[idx.status] === 'published';
  });
  if (!match) return { error: 'Article not found' };
  return {
    title: match[idx.title],
    bodyHtml: match[idx.body_html],
    updatedAt: match[idx.updated_at],
  };
}

function handleSaveArticle_(data) {
  const title = (data.title || '').trim();
  const slug = slugify_(data.slug || data.title);
  if (!title || !slug) return { error: 'Title (and slug) are required' };

  const rowsData = articleRowsIndexed_();
  const idx = rowsData.idx;
  const now = new Date().toISOString();

  if (data.articleId) {
    const rowIndex = rowsData.rows.findIndex(function (row) { return row[idx.article_id] === data.articleId; });
    if (rowIndex === -1) return { error: 'Article not found' };
    const slugTaken = rowsData.rows.some(function (row, i) {
      return i !== rowIndex && row[idx.slug] === slug;
    });
    if (slugTaken) return { error: 'That slug is already used by another article' };
    const sheetRow = rowIndex + 2; // +1 for header, +1 for 1-indexing
    rowsData.sheet.getRange(sheetRow, idx.slug + 1).setValue(slug);
    rowsData.sheet.getRange(sheetRow, idx.title + 1).setValue(title);
    rowsData.sheet.getRange(sheetRow, idx.body_html + 1).setValue(data.bodyHtml || '');
    rowsData.sheet.getRange(sheetRow, idx.status + 1).setValue(data.status || 'draft');
    rowsData.sheet.getRange(sheetRow, idx.updated_at + 1).setValue(now);
    return { articleId: data.articleId, slug: slug };
  }

  const slugTaken = rowsData.rows.some(function (row) { return row[idx.slug] === slug; });
  if (slugTaken) return { error: 'That slug is already used by another article' };
  const articleId = Utilities.getUuid();
  rowsData.sheet.appendRow([articleId, slug, title, data.bodyHtml || '', data.status || 'draft', now, now]);
  return { articleId: articleId, slug: slug };
}

function handleDeleteArticle_(data) {
  const rowsData = articleRowsIndexed_();
  const idx = rowsData.idx;
  const rowIndex = rowsData.rows.findIndex(function (row) { return row[idx.article_id] === data.articleId; });
  if (rowIndex === -1) return { error: 'Article not found' };
  rowsData.sheet.deleteRow(rowIndex + 2);
  return { deleted: true };
}

function getOrCreateFolder_(name) {
  const folders = DriveApp.getFoldersByName(name);
  if (folders.hasNext()) return folders.next();
  return DriveApp.createFolder(name);
}

function handleUploadImage_(data) {
  if (!data.imageBase64 || !data.mimeType) return { error: 'imageBase64 and mimeType are required' };
  const folder = getOrCreateFolder_(ARTICLE_IMAGES_FOLDER_NAME);
  const decoded = Utilities.base64Decode(data.imageBase64);
  const blob = Utilities.newBlob(decoded, data.mimeType, data.filename || 'image');
  const file = folder.createFile(blob);
  file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
  return { url: 'https://lh3.googleusercontent.com/d/' + file.getId() };
}

// Actions each require their own password, checked before dispatch:
// - EXAM_ACTIONS: the exam-taker's GATE_PASSWORD (existing behavior, unchanged).
// - ADMIN_ACTIONS: the admin panel's ADMIN_PASSWORD (a different audience/secret).
// - Anything not listed in either (e.g. getArticle) is public — no password.
const EXAM_ACTIONS = ['register', 'submit', 'leaderboard'];
const ADMIN_ACTIONS = ['listArticles', 'saveArticle', 'deleteArticle', 'uploadImage'];

function doPost(e) {
  let data;
  try {
    data = JSON.parse(e.postData.contents);
  } catch (err) {
    return jsonResponse_({ error: 'Invalid JSON body' });
  }

  if (EXAM_ACTIONS.indexOf(data.action) !== -1 && data.password !== GATE_PASSWORD) {
    return jsonResponse_({ error: 'Incorrect password' });
  }
  if (ADMIN_ACTIONS.indexOf(data.action) !== -1 && data.adminPassword !== ADMIN_PASSWORD) {
    return jsonResponse_({ error: 'Incorrect admin password' });
  }

  let result;
  switch (data.action) {
    case 'register':
      result = handleRegister_(data);
      break;
    case 'submit':
      result = handleSubmit_(data);
      break;
    case 'leaderboard':
      result = handleLeaderboard_();
      break;
    case 'getArticle':
      result = handleGetArticle_(data);
      break;
    case 'listArticles':
      result = handleListArticles_();
      break;
    case 'saveArticle':
      result = handleSaveArticle_(data);
      break;
    case 'deleteArticle':
      result = handleDeleteArticle_(data);
      break;
    case 'uploadImage':
      result = handleUploadImage_(data);
      break;
    default:
      result = { error: 'Unknown action: ' + data.action };
  }
  return jsonResponse_(result);
}

function doGet(e) {
  return jsonResponse_({ status: 'CTFL Exam API is running' });
}
